<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RhonAyro.Client.Desktop.Ui</RootNamespace>
        <AssemblyName>RhonAyro.Client.Desktop.Ui</AssemblyName>
        <PackageId>RhonAyro.Client.Desktop.Ui</PackageId>
        <Authors>RhonAyro.Client.Desktop.Ui</Authors>
        <OutputPath>..\..\build\$(Configuration)\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <WarningsAsErrors />
        <NoWarn />
        <DocumentationFile>..\..\build\$(Configuration)\RhonAyro.Client.Desktop.Ui.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DefineConstants>TRACE</DefineConstants>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <WarningsAsErrors />
        <NoWarn />
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Properties\" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\VersionInfo.cs" Link="Properties\VersionInfo.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RhonAyro.Infrastructure.Runtime\RhonAyro.Infrastructure.Runtime.csproj" />
      <ProjectReference Include="..\RhonAyro.Infrastructure.Storage\RhonAyro.Infrastructure.Storage.csproj" />
    </ItemGroup>

</Project>
